language: python
python:
  - "3.6"

install:
  - pip install kodi-addon-checker

script:
  - printf "%s\n" "$TRAVIS_COMMIT_RANGE"
  - |
    rm -rf LICENSES/
    cd $HOME
    kodi-addon-checker $TRAVIS_BUILD_DIR --branch=isengard
