language: python
python:
  - "3.6"

install:
  - pip install kodi-addon-checker

script:
  - |
    export COMMIT_COUNT=$(($(git rev-list --count $TRAVIS_COMMIT_RANGE) - 1))
    printf "%s" "$COMMIT_COUNT"
