language: python
python:
  - "3.6"

install:
  - pip install kodi-addon-checker

script:
  - |
    rm -rf LICENSES/
    cd $HOME
    kodi-addon-checker $TRAVIS_BUILD_DIR --branch=isengard

notifications:
  webhooks: https://www.travisbuddy.com/
  email:
    on_failure: change

travisBuddy:
  successBuildLog: true
